

jwt:
  signing-key: "please do us a favor and change this to a SHA256 real key"
  issuer: "your-service-name-here"
  expiration-seconds: 120

authorization:
  consent-url: https://my-app.com/oauth2/authorize

oauth2-server:
  allowed-response-types: ["code", "token"]